<?php
// ENTER THE USERNAME YOU WANT EMAILED TO YOU
$user = "USERNAME";

// ENTER YOUR EMAIL ADDRESS
$your_email = "YOUREMAIL";

// ENTER EITHER YOUR EMAIL OR IF YOU WANT TO REPLY TO YOUR FRIEND VIA EMAIL, YOU CAN USE THEIRS
$email = "EMAIL";

?>